[package]
name = "salvage_job_kicker"
version = "0.1.0"
authors = ["Ryota Kameoka <kameoka.ryota@gmail.com>"]

[dependencies]
env_logger = "0.5"
log = "0.4"
reqwest = "0.8"
rusoto_core = "0.33.0"
rusoto_sqs = "0.33.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"